## 5.4 Self-Defined Layers

### 5.4.1 Layers without Parameters

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()
    
  def forward(self, X):
    return X - X.mean()

In [5]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

### 5.4.2 Layers with Parameters

In [3]:
class MyLinear(nn.Module):
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units))
    self.bias = nn.Parameter(torch.randn(units,))
  def forward(self, X):
    linear = torch.matmul(X, self.weight.data) + self.bias.data
    return F.relu(linear)

linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[-9.3269e-01,  2.0951e-01, -2.7894e+00],
        [ 2.2814e+00,  4.3191e-02, -5.4345e-01],
        [-1.4957e+00, -1.3567e-01,  1.0360e+00],
        [-5.4145e-01, -7.3059e-02, -7.2200e-01],
        [ 3.9249e-01,  1.7180e-03, -1.7124e+00]], requires_grad=True)

In [4]:
linear(torch.rand(2, 5))

tensor([[1.4042, 0.0000, 0.0000],
        [0.0000, 0.1696, 0.0000]])

In [7]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[12.2160],
        [14.0700]])